site_name: x
repo_name: longxuhu/x
repo_url: https://github.com/longxuhu/x
copyright: Copyright &copy; 2025 Xiao Han
theme:
  name: material
  language: zh
  custom_dir: overrides
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    repo: fontawesome/brands/github
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
    - content.code.select
    - content.code.copy
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
  - search
  - tags
  - blog:
      authors_profiles: true
      pagination_per_page: 10
      archive_pagination_per_page: 10
      categories_pagination_per_page: 10
      authors_file: "{blog}/.authors.yaml"
      draft: true
markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
nav:
  - 主页: index.md
  - 读书划线:
      - 2025:
          - 种草: books/2025/inspire-lives.md
      - 2024:
          - 运动改变大脑: books/2024/move.md
          - 如何成为不完美主义者: books/2024/how-to-be-an-imperfectionist.md
          - 从0到1: books/2024/zero-to-one.md
          - 解码商业模式: books/2024/decoding-the-business-model.md
          - 好运: books/2024/fortune.md
          - 汴京之围: books/2024/1126-the-siege-of-bianjing.md
          - 解构现代化: books/2024/decoupling-the-modernization.md
          - 数字极简: books/2024/digital-minimalism.md
          - 怎样做成大事: books/2024/how-big-things-get-done.md
          - 太白金星有点烦: books/2024/the-annoyance-of-the-gods.md
          - 三国争霸: books/2024/3rd-kingdom.md
          - 见识: books/2024/jianshi.md
          - 大败局: books/2024/dabaiju.md
          - 掌控习惯: books/2024/atomic-habits.md
      - 2023:
          - 底层逻辑2: books/2023/the-underlying-logic-2.md
          - AI未来进行式: books/2023/ai-2041.md
          - 纳瓦尔宝典: books/2023/the-almanack-of-naval-ravikant.md
      - 2022:
          - 持续交付: books/2022/continuous-delivery.md
          - 启示录: books/2022/inspired.md
          - 独角兽项目: books/2022/the-unicorn-project.md
          - 增长黑客: books/2022/hacking-growth.md
      - 2021:
          - 城里的房子: books/2021/house-in-city.md
          - 上游思维: books/2021/upstream.md
          - 闪电式扩张: books/2021/blitzscaling.md
          - 贝佐斯致股东的信: books/2021/the-bezos-letters.md
          - 创新者的窘境: books/2021/the-innovator's-dilemma.md
          - 思考，快与慢: books/2021/thinking-fast-and-slow.md
          - 这就是OKR: books/2021/measure-what-matters.md
          - 大教堂与集市: books/2021/the-cathedral-and-the-bazaar.md
          - 格局: books/2021/geju.md
      - 2020:
          - 奈飞文化手册: books/2020/powerful.md
          - 大数据时代: books/2020/big-data.md
          - 群体性孤独: books/2020/alone-together.md
          - 高效程序员的45个习惯: books/2020/practices-of-an-agile-developer.md
          - 人体简史: books/2020/the-body.md
          - AI 新生: books/2020/human-compatible.md
          - 黑客与画家: books/2020/hackers-and-painters.md
          - 像火箭科学家一样思考: books/2020/think-like-a-rocket-scientist.md
  - 代码片段:
      - 企业微信加解密库: snippets/wecom-biz-msg-crypt3.md
  - Tips:
      - Gitlab换成国内公共头像服务: tips/gitlab-public-avatar.md
  - 日记:
      - blog/index.md
