name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Cache mkdocs-material and pip dependencies
        uses: actions/cache@v4
        with:
          path: |
            .cache
            ~/.cache/pip
          key: mkdocs-material-${{ github.run_id }}
          restore-keys: |
            mkdocs-material-

      - name: Install dependencies
        run: pip install mkdocs-material

      - name: Build and Deploy
        env:
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
        run: mkdocs gh-deploy --force